# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Message(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, code=None, success=None):  # noqa: E501
        """Message - a model defined in OpenAPI

        :param message: The message of this Message.  # noqa: E501
        :type message: str
        :param code: The code of this Message.  # noqa: E501
        :type code: int
        :param success: The success of this Message.  # noqa: E501
        :type success: bool
        """
        self.openapi_types = {
            'message': str,
            'code': int,
            'success': bool
        }

        self.attribute_map = {
            'message': 'message',
            'code': 'code',
            'success': 'success'
        }

        self._message = message
        self._code = code
        self._success = success

    @classmethod
    def from_dict(cls, dikt) -> 'Message':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Message of this Message.  # noqa: E501
        :rtype: Message
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self):
        """Gets the message of this Message.


        :return: The message of this Message.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Message.


        :param message: The message of this Message.
        :type message: str
        """

        self._message = message

    @property
    def code(self):
        """Gets the code of this Message.


        :return: The code of this Message.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Message.


        :param code: The code of this Message.
        :type code: int
        """

        self._code = code

    @property
    def success(self):
        """Gets the success of this Message.


        :return: The success of this Message.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this Message.


        :param success: The success of this Message.
        :type success: bool
        """

        self._success = success
