# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Platform(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PLAYSTATION_5 = "playstation-5"
    PLAYSTATION_4 = "playstation-4"
    PLAYSTATION_3 = "playstation-3"
    PLAYSTATION_2 = "playstation-2"
    PLAYSTATION_1 = "playstation-1"
    NINTENDO_SWITCH = "nintendo-switch"
    NINTENDO_WII = "nintendo-wii"
    GAME_CUBE = "game-cube"
    NINTENDO_64 = "nintendo-64"
    SUPER_NINTENDO = "super-nintendo"
    XBOX_SERIES_X = "xbox-series-x"
    XBOX_ONE = "xbox-one"
    XBOX_360 = "xbox-360"
    PC = "pc"
    def __init__(self):  # noqa: E501
        """Platform - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Platform':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Platform of this Platform.  # noqa: E501
        :rtype: Platform
        """
        return util.deserialize_model(dikt, cls)
